-- V1__init.sql

CREATE TABLE
    companies (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(120) NOT NULL,
        vat_number VARCHAR(32),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id BIGINT NOT NULL,
        email VARCHAR(190) NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        role VARCHAR(32) NOT NULL,
        enabled BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies (id),
        CONSTRAINT uq_users_company_email UNIQUE (company_id, email),
        CONSTRAINT ck_users_role CHECK (
            role IN ('PLATFORM_ADMIN', 'COMPANY_MANAGER', 'BACK_OFFICE')
        )
    );