CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,

    display_name    VARCHAR(160) NOT NULL,
    legal_name      VARCHAR(200),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    email           VARCHAR(254),
    phone           VARCHAR(40),

    vat_number      VARCHAR(20) NOT NULL,
    pec             VARCHAR(254),

    address   VARCHAR(200),
    city            VARCHAR(120),
    postal_code     VARCHAR(20),
    country         VARCHAR(2) DEFAULT 'IT',

    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_customers_company FOREIGN KEY (company_id) REFERENCES companies(id)
    CONSTRAINT ck_customer_status CHECK (
        status IN ('ACTIVE', 'ARCHIVED', 'DELETED')
    )
);

-- Indici
CREATE INDEX IF NOT EXISTS idx_customers_company_id ON customers(company_id);
CREATE INDEX IF NOT EXISTS idx_customers_display_name ON customers(display_name);
-- Unicità per company e P.IVA
CREATE UNIQUE INDEX IF NOT EXISTS ux_customers_company_vat ON customers(company_id, vat_number);