CREATE TABLE IF NOT EXISTS quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id  BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,

    quote_year   INT NOT NULL,
    quote_number INT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    title VARCHAR(200),
    notes VARCHAR(2000),

    issue_date  DATE NOT NULL DEFAULT CURRENT_DATE,
    valid_until DATE,

    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',

    subtotal_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    tax_amount      NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_amount    NUMERIC(19,2) NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_quotes_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_quotes_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT uq_quotes_company_year_number UNIQUE (company_id, quote_year, quote_number),
    CONSTRAINT ck_quotes_status CHECK (status IN ('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CONVERTED', 'ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS idx_quotes_company_id ON quotes(company_id);
CREATE INDEX IF NOT EXISTS idx_quotes_customer_id ON quotes(customer_id);
CREATE INDEX IF NOT EXISTS idx_quotes_company_status ON quotes(company_id, status);
CREATE INDEX IF NOT EXISTS idx_quotes_company_issue_date ON quotes(company_id, issue_date);

-- Quote_Items
CREATE TABLE IF NOT EXISTS quote_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    quote_id BIGINT NOT NULL,
    position INT NOT NULL,

    description VARCHAR(1000) NOT NULL,
    notes VARCHAR(1000),

    quantity   NUMERIC(19,4) NOT NULL DEFAULT 1,
    unit       VARCHAR(20),
    unit_price NUMERIC(19,4) NOT NULL DEFAULT 0,

    tax_rate NUMERIC(5,2) NOT NULL DEFAULT 0,

    discount_type  VARCHAR(20) NOT NULL DEFAULT 'NONE',
    discount_value NUMERIC(19,4) NOT NULL DEFAULT 0,

    line_subtotal_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    line_tax_amount      NUMERIC(19,2) NOT NULL DEFAULT 0,
    line_total_amount    NUMERIC(19,2) NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_quote_items_quote FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE CASCADE,
    CONSTRAINT uq_quote_items_quote_position UNIQUE (quote_id, position),
    CONSTRAINT ck_quote_items_discount_type CHECK (discount_type IN ('NONE', 'PERCENT', 'AMOUNT'))
);

CREATE INDEX IF NOT EXISTS idx_quote_items_quote_id ON quote_items(quote_id);