CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id  BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    source_quote_id BIGINT,

    invoice_year   INT NOT NULL,
    invoice_number INT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    title VARCHAR(200),
    notes VARCHAR(2000),

    issue_date  DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date    DATE,

    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',

    subtotal_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    tax_amount      NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_amount    NUMERIC(19,2) NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invoices_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_invoices_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_invoices_source_quote FOREIGN KEY (source_quote_id) REFERENCES quotes(id),
    CONSTRAINT uq_invoices_company_year_number UNIQUE (company_id, invoice_year, invoice_number),
    CONSTRAINT ck_invoices_status CHECK (status IN ('DRAFT', 'ISSUED', 'PAID', 'OVERDUE'))
);

CREATE INDEX IF NOT EXISTS idx_invoices_company_id ON invoices(company_id);
CREATE INDEX IF NOT EXISTS idx_invoices_customer_id ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_source_quote_id ON invoices(source_quote_id);
CREATE INDEX IF NOT EXISTS idx_invoices_company_status ON invoices(company_id, status);
CREATE INDEX IF NOT EXISTS idx_invoices_company_issue_date ON invoices(company_id, issue_date);

CREATE TABLE IF NOT EXISTS invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    invoice_id BIGINT NOT NULL,
    position INT NOT NULL,

    description VARCHAR(1000) NOT NULL,
    notes VARCHAR(1000),

    quantity   NUMERIC(19,4) NOT NULL DEFAULT 1,
    unit       VARCHAR(20),
    unit_price NUMERIC(19,4) NOT NULL DEFAULT 0,

    tax_rate NUMERIC(5,2) NOT NULL DEFAULT 0,

    discount_type  VARCHAR(20) NOT NULL DEFAULT 'NONE',
    discount_value NUMERIC(19,4) NOT NULL DEFAULT 0,

    line_subtotal_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    line_tax_amount      NUMERIC(19,2) NOT NULL DEFAULT 0,
    line_total_amount    NUMERIC(19,2) NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    CONSTRAINT uq_invoice_items_invoice_position UNIQUE (invoice_id, position),
    CONSTRAINT ck_invoice_items_discount_type CHECK (discount_type IN ('NONE', 'PERCENT', 'AMOUNT'))
);

CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice_id ON invoice_items(invoice_id);