CREATE TABLE invoice_pdf_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    path VARCHAR(1024) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_invoice_pdf_archive_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    CONSTRAINT uq_invoice_pdf_archive_path_filename UNIQUE (path, file_name)
);

CREATE INDEX idx_invoice_pdf_archive_invoice_created ON invoice_pdf_archive (invoice_id, created_at DESC);
CREATE INDEX idx_invoice_pdf_archive_invoice ON invoice_pdf_archive (invoice_id);